apiVersion: v1
kind: ConfigMap
data:
  default.conf: |
    upstream backend {
      # DNS SRV is only supported by nginx-plus :(
      # server app-service.default service=_app._tcp resolve max_fails=0;
      server bookapi.default:3000 max_fails=0;
    }

    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;
            listen 443 ssl;
            server_name localhost;
            ssl_certificate /etc/nginx/ssl/cert;
            ssl_certificate_key /etc/nginx/ssl/key;

            location / {
                    proxy_pass http://backend;
            }
    }
metadata:
  name: nginx
